name: inventory_mobile
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  core:
    path: ../../packages/core
  data:
    path: ../../packages/data
  auth:
    path: ../../packages/features/auth
  inventory:
    path: ../../packages/features/inventory
  reports:
    path: ../../packages/features/reports
  common_widgets:
    path: ../../packages/features/common_widgets

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
