name: inventory
description: Main inventory management feature.
version: 0.0.1
publish_to: 'none'

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  core:
    path: ../../core
  data:
    path: ../../data
  common_widgets:
    path: ../common_widgets
  flutter_riverpod: ^2.4.0
  mobile_scanner: ^5.0.0
  uuid: ^4.0.0
  geolocator: ^12.0.0
  geocoding: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
