name: reports
description: Reporting and analytics feature.
version: 0.0.1
publish_to: 'none'

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  core:
    path: ../../core
  data:
    path: ../../data
  common_widgets:
    path: ../common_widgets

dev_dependencies:
  flutter_test:
    sdk: flutter
